/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sixela
 */
import accesobase.ConexionAccess;
import javax.swing.JOptionPane;

public class clientess extends javax.swing.JDialog {

    int puntero = 1,clienteoseguro=0;
    

    /**
     * Creates new form clientess
     */
    public ConexionAccess BD_ACCESS = new ConexionAccess();

    public clientess(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtdni.setEnabled(true);
        onoffcomponenetes(false);
        jbbaja.setEnabled(false);
        jbmodificacion.setEnabled(false);
        jbalta.setEnabled(false);
        jpseguros.setVisible(false);

    }
boolean resultadotelefono=false,resultadoemail=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void onoffcomponenetes(boolean valor) {

        txtnombre.setEnabled(valor);
        txtapellidos.setEnabled(valor);
        cbedad.setEnabled(valor);
        txtcalle.setEnabled(valor);
        txtciudad.setEnabled(valor);
        txttelefono.setEnabled(valor);
        txtemail.setEnabled(valor);
        cbsexo.setEnabled(valor);

    }

    public void limpiar() {
        txtdni.setText("");
        txtnombre.setText("");
        txtapellidos.setText("");
        cbedad.setSelectedIndex(1);
        txtcalle.setText("");
        txtciudad.setText("");
        txttelefono.setText("");
        txtemail.setText("");
        cbsexo.setSelectedIndex(1);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgsexo = new javax.swing.ButtonGroup();
        jbalta = new javax.swing.JButton();
        jbbaja = new javax.swing.JButton();
        jbmodificacion = new javax.swing.JButton();
        jbvolver = new javax.swing.JButton();
        jpaneldatoscliente = new javax.swing.JPanel();
        lbapellidos = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lbnombre = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        lbciudad = new javax.swing.JLabel();
        lbcalle = new javax.swing.JLabel();
        txtcalle = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        lbdni = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        lbtelefono = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        lbemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lbedad = new javax.swing.JLabel();
        cbedad = new javax.swing.JComboBox();
        lbdatospersonales = new javax.swing.JLabel();
        jbsexo = new javax.swing.JLabel();
        cbsexo = new javax.swing.JComboBox();
        jbcomprobar = new javax.swing.JButton();
        jpseguros = new javax.swing.JPanel();
        jstabla = new javax.swing.JScrollPane();
        jtresultados = new javax.swing.JTable();
        jbseguros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbalta.setText("ALTA");
        jbalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaltaActionPerformed(evt);
            }
        });

        jbbaja.setText("BAJA");
        jbbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbajaActionPerformed(evt);
            }
        });

        jbmodificacion.setText("MODIFICACION");
        jbmodificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificacionActionPerformed(evt);
            }
        });

        jbvolver.setText("VOLVER");
        jbvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbvolverActionPerformed(evt);
            }
        });

        jpaneldatoscliente.setBackground(new java.awt.Color(255, 255, 255));
        jpaneldatoscliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpaneldatoscliente.setOpaque(false);

        lbapellidos.setText("Apellidos");

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        lbnombre.setText("Nombre");

        lbciudad.setText("Ciudad");

        lbcalle.setText("Calle");

        txtciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciudadActionPerformed(evt);
            }
        });
        txtciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciudadKeyTyped(evt);
            }
        });

        lbdni.setText("DNI");

        txtdni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdniFocusLost(evt);
            }
        });

        lbtelefono.setText("Telefono");

        txttelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelefonoFocusLost(evt);
            }
        });
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        lbemail.setText("Email");

        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });

        lbedad.setText("Edad");

        cbedad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", " " }));

        lbdatospersonales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbdatospersonales.setText("DATOS PERSONALES");

        jbsexo.setText("Sexo");

        cbsexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));

        jbcomprobar.setText("Comprobar");
        jbcomprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcomprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaneldatosclienteLayout = new javax.swing.GroupLayout(jpaneldatoscliente);
        jpaneldatoscliente.setLayout(jpaneldatosclienteLayout);
        jpaneldatosclienteLayout.setHorizontalGroup(
            jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbdatospersonales)
                    .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                        .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                                .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbedad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbdni, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbcomprobar))))
                            .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                                .addComponent(lbcalle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtcalle, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                                .addComponent(lbciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                                .addComponent(lbtelefono)
                                .addGap(54, 54, 54)
                                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                                .addComponent(lbemail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                                .addComponent(jbsexo)
                                .addGap(72, 72, 72)
                                .addComponent(cbsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpaneldatosclienteLayout.setVerticalGroup(
            jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneldatosclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbdatospersonales)
                .addGap(22, 22, 22)
                .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdni)
                    .addComponent(lbciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbcomprobar))
                .addGap(18, 18, 18)
                .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtelefono)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbedad)
                    .addComponent(cbsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsexo))
                .addGap(28, 28, 28)
                .addGroup(jpaneldatosclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcalle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcalle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jtresultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Tittle 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jstabla.setViewportView(jtresultados);
        if (jtresultados.getColumnModel().getColumnCount() > 0) {
            jtresultados.getColumnModel().getColumn(0).setResizable(false);
            jtresultados.getColumnModel().getColumn(1).setResizable(false);
            jtresultados.getColumnModel().getColumn(2).setResizable(false);
            jtresultados.getColumnModel().getColumn(3).setResizable(false);
        }

        jbseguros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbseguros.setText("SEGUROS");

        javax.swing.GroupLayout jpsegurosLayout = new javax.swing.GroupLayout(jpseguros);
        jpseguros.setLayout(jpsegurosLayout);
        jpsegurosLayout.setHorizontalGroup(
            jpsegurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsegurosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpsegurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jstabla)
                    .addGroup(jpsegurosLayout.createSequentialGroup()
                        .addComponent(jbseguros)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpsegurosLayout.setVerticalGroup(
            jpsegurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsegurosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbseguros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jstabla, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpaneldatoscliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(907, 907, 907)
                        .addComponent(jbvolver)
                        .addGap(18, 18, 18)
                        .addComponent(jbalta)
                        .addGap(18, 18, 18)
                        .addComponent(jbbaja)
                        .addGap(18, 18, 18)
                        .addComponent(jbmodificacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpseguros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpaneldatoscliente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpseguros, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbalta)
                    .addComponent(jbbaja)
                    .addComponent(jbmodificacion)
                    .addComponent(jbvolver))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaltaActionPerformed
        String SentenciaSQL = "INSERT INTO cliente2 (dni,nombre,apellidos,telefono,edad,calle,ciudad,email,sexo) VALUES ('"
                + txtdni.getText() + "','" + txtnombre.getText() + "','" + txtapellidos.getText() + "','" + txttelefono.getText() + "'," + cbedad.getSelectedItem() + ",'" + txtcalle.getText() + "','" + txtciudad.getText() + "','" + txtemail.getText() + "','" + cbsexo.getSelectedItem() + "')";
        this.BD_ACCESS.InsertInsertar(SentenciaSQL);
        limpiar();
        txtdni.setEnabled(true);
        onoffcomponenetes(false);
        jpseguros.setVisible(false);
        jbcomprobar.setEnabled(true);

    }//GEN-LAST:event_jbaltaActionPerformed

    private void txtciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciudadActionPerformed

    private void jbvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbvolverActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbvolverActionPerformed

    private void txtdniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdniFocusLost
        /*
         String cadenas[];
         String Sentencia="SELECT * FROM cliente2 where dni like '"+txtdni.getText()+"'";
      
         boolean resultado=false;
         resultado=clientess.isNifValido(txtdni.getText());
         if(resultado==true){
         cadenas=BD_ACCESS.ConsultarRegistro(Sentencia,puntero);
         if(cadenas[0]==""){
         onoffcomponenetes(true);
         txtdni.setEnabled(false);
         }else{
         txtdni.setEnabled(false);
         onoffcomponenetes(true);
         txtnombre.setText(cadenas[1]);
         txtapellidos.setText(cadenas[2]);
         txttelefono.setText(cadenas[3]);
         cbedad.setSelectedItem(cadenas[4]);
         txtcalle.setText(cadenas[5]);
         txtciudad.setText(cadenas[6]);
         txtemail.setText(cadenas[7]);
         cbsexo.setSelectedItem(cadenas[8]);
         puntero=Integer.parseInt(cadenas[9]);          // TODO add your handling code here:
         }
         }else {
         JOptionPane.showMessageDialog(null,"DNI INTRODUCIDO  NO  VALIDO");
         }*/
    }//GEN-LAST:event_txtdniFocusLost

    private void txttelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefonoFocusLost
        String tamaño;
        tamaño = txttelefono.getText();

        if (tamaño.equals("")) {
        } else {
            if (tamaño.length() != 9) {
                System.out.println("esta mal el telefono");
                txttelefono.requestFocus(true);
          JOptionPane.showMessageDialog(this,"el telefono introducido es incorrecto");
                //JOptionPane.showMessageDialog(this, "Este es un mensaje detallado", "éxito!", JOptionPane.WARNING_MESSAGE);
           /*salen 2 veces los joptionpane*/
            }else{resultadotelefono=true;}

        }

    }//GEN-LAST:event_txttelefonoFocusLost

    private void jbcomprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcomprobarActionPerformed

        String cadenas[];
        String Sentencia = "SELECT * FROM cliente2 where dni like '" + txtdni.getText() + "'";

        boolean resultado = false;
        resultado = clientess.isNifValido(txtdni.getText());
        if (resultado == true) {
            try {
                cadenas = BD_ACCESS.ConsultarRegistro(Sentencia, puntero,clienteoseguro);

                if (cadenas[0] == "") {
                    onoffcomponenetes(true);
                    txtdni.setEnabled(false);
                } else {
                    txtdni.setEnabled(false);
                    onoffcomponenetes(true);
                    jbcomprobar.setEnabled(false);
                    txtnombre.setText(cadenas[1]);
                    txtapellidos.setText(cadenas[2]);
                    txttelefono.setText(cadenas[3]);
                    cbedad.setSelectedItem(cadenas[4]);
                    txtcalle.setText(cadenas[5]);
                    txtciudad.setText(cadenas[6]);
                    txtemail.setText(cadenas[7]);
                    cbsexo.setSelectedItem(cadenas[8]);
                    puntero = Integer.parseInt(cadenas[9]);
                    String SentenciaSQL = "SELECT * FROM seguros2 where clientedni like '" + txtdni.getText() + "'";
                    jtresultados.setModel(this.BD_ACCESS.SelectConsultar(SentenciaSQL));
                    jbbaja.setEnabled(true);
                    jbmodificacion.setEnabled(true);
                    jbalta.setEnabled(false);
                    jpseguros.setVisible(true);

                }
            } catch (java.lang.NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "NO EXISTE REGITRO CON ESTE DNI\nCREA  ALTA PARA EL CLIENTE");
                jbbaja.setEnabled(false);
                jbmodificacion.setEnabled(false);
                jbalta.setEnabled(true);

                //como salta error de que no hay registro hay que activar los botones y desactivarlos desde el catch porque si no esxite registro solo puede dar error o no
            }
        } else {
            JOptionPane.showMessageDialog(null, "DNI INTRODUCIDO  NO  VALIDO");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jbcomprobarActionPerformed

    private void jbbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbajaActionPerformed
        String SentenciaSQL = "DELETE FROM cliente2 WHERE dni = '" + txtdni.getText() + "'";
        this.BD_ACCESS.DeleteEliminar(SentenciaSQL);
        limpiar();
        txtdni.setEnabled(true);
        onoffcomponenetes(false);
        jpseguros.setVisible(false);
        jbcomprobar.setEnabled(true);
    }//GEN-LAST:event_jbbajaActionPerformed

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped

        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z')) {
            evt.consume();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciudadKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z')) {
            evt.consume();       }  // TODO add your handling code here:
    }//GEN-LAST:event_txtciudadKeyTyped

    private void jbmodificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificacionActionPerformed
txttelefonoFocusLost(null);
txtemailFocusLost(null);
   if(resultadotelefono==true && resultadoemail==true){
        String SentenciaSQL = "UPDATE cliente2 SET dni = '" + txtdni.getText() + 
                "',nombre = '" + txtnombre.getText() + "',apellidos = '" + txtapellidos.getText() + 
                "',edad = '" + cbedad.getSelectedItem() + 
                "',calle = '" + txtcalle.getText() + "' ,ciudad = '"+txtciudad.getText()+"',telefono = '"+txttelefono.getText()+"', email='"+txtemail.getText()+
                "' WHERE dni = '" + txtdni.getText() + "';";
        this.BD_ACCESS.UpdateModificar(SentenciaSQL);
        limpiar();
        txtdni.setEnabled(true);
        onoffcomponenetes(false);
        jpseguros.setVisible(false);
        jbcomprobar.setEnabled(true);
       jbmodificacion.setEnabled(false);
        jbbaja.setEnabled(false);
}
   resultadotelefono=false;
   resultadoemail=false;
    }//GEN-LAST:event_jbmodificacionActionPerformed

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        
 resultadoemail=clientess.validarmail(txtemail.getText());
 if(resultadoemail==true){}else{
 JOptionPane.showMessageDialog(this,"el email introducido es incorrecto");
 txtemail.requestFocus();
 }
    }//GEN-LAST:event_txtemailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                clientess dialog = new clientess(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public static boolean isNifValido(String nif) {

        boolean resultado = false;
        String LETRAS_NIF = "TRWAGMYFPDXBNJZSQVHLCKE";

        try {
            String nif1 = nif.toUpperCase();
            if (nif1.matches("[0-9]{8}[" + LETRAS_NIF + "]")) {
                int dni = Integer.parseInt(nif1.substring(0, 8));
                char letraCalculada = LETRAS_NIF.charAt(dni % 23);
                if (letraCalculada == nif1.charAt(8)) {
                    resultado = true;
                }
            }
        } catch (Exception e) {
            // Si ha habido alg�n error es porque hay alg�n parseo que tira bien.
            resultado = false;
        }

        return resultado;
    }
public static boolean validarmail(String correo) {
    
    int longitud = correo.length();
    char valor;
    boolean resultado=false;
    
    for(char i = 0; i < longitud; i++)
    {
    valor = correo.charAt(i);
        if(valor == '@' && i == 0){
        
        break;
        }
    	if(valor == '@')
    	{
    	
        
        resultado=true;
    	break;
    	}
    	else if(i == longitud-1){
    	 
         
         
    	 break;
    		
    	}
    	
    	
      }
		System.out.println("resultado vale"+resultado);
    return resultado;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgsexo;
    private javax.swing.JComboBox cbedad;
    private javax.swing.JComboBox cbsexo;
    private javax.swing.JButton jbalta;
    private javax.swing.JButton jbbaja;
    private javax.swing.JButton jbcomprobar;
    private javax.swing.JButton jbmodificacion;
    private javax.swing.JLabel jbseguros;
    private javax.swing.JLabel jbsexo;
    private javax.swing.JButton jbvolver;
    private javax.swing.JPanel jpaneldatoscliente;
    private javax.swing.JPanel jpseguros;
    private javax.swing.JScrollPane jstabla;
    private javax.swing.JTable jtresultados;
    private javax.swing.JLabel lbapellidos;
    private javax.swing.JLabel lbcalle;
    private javax.swing.JLabel lbciudad;
    private javax.swing.JLabel lbdatospersonales;
    private javax.swing.JLabel lbdni;
    private javax.swing.JLabel lbedad;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbtelefono;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcalle;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
